# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "20480"
  end

  config.vm.provision :shell do |s|
    s.path = 'vagrant/provision.sh'
  end

end
